[features]
seeds = false
skip-lint = false

[programs.localnet]
zipper = "Z1PrGTgZp5Q1WKewjF4XaTW2nHvNxvbxs7qW8p9qz5U"

[programs.testnet]
zipper = "Z1PrGTgZp5Q1WKewjF4XaTW2nHvNxvbxs7qW8p9qz5U"

[programs.mainnet]
zipper = "Z1PrGTgZp5Q1WKewjF4XaTW2nHvNxvbxs7qW8p9qz5U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./dev_key.json"

[scripts]
test = "cargo test --package zipper --test spoof -- l spoof --exact --nocapture"
