[features]
seeds = false
skip-lint = false

[programs.localnet]
zipper = "Z1PctcuGZfcLVPWSCgi9nwhGNpvqH1AamRTEqSBzJoL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./dev_key.json"

[scripts]
test = "cargo test --package zipper --test spoof -- spoof --exact --nocapture"
